export const LATEX_COMMANDS = [
  { name: 'documentclass', snippet: 'documentclass{article}', meta: 'structure' },
  { name: 'usepackage', snippet: 'usepackage{', meta: 'structure' },
  { name: 'begin', snippet: 'begin{', meta: 'structure' },
  { name: 'end', snippet: 'end{', meta: 'structure' },
  { name: 'input', snippet: 'input{', meta: 'structure' },
  { name: 'include', snippet: 'include{', meta: 'structure' },
  { name: 'title', snippet: 'title{', meta: 'structure' },
  { name: 'author', snippet: 'author{', meta: 'structure' },
  { name: 'date', snippet: 'date{', meta: 'structure' },
  { name: 'maketitle', snippet: 'maketitle', meta: 'structure' },
  { name: 'tableofcontents', snippet: 'tableofcontents', meta: 'structure' },
  { name: 'listoffigures', snippet: 'listoffigures', meta: 'structure' },
  { name: 'listoftables', snippet: 'listoftables', meta: 'structure' },
  { name: 'appendix', snippet: 'appendix', meta: 'structure' },
  { name: 'part', snippet: 'part{', meta: 'section' },
  { name: 'chapter', snippet: 'chapter{', meta: 'section' },
  { name: 'section', snippet: 'section{', meta: 'section' },
  { name: 'subsection', snippet: 'subsection{', meta: 'section' },
  { name: 'subsubsection', snippet: 'subsubsection{', meta: 'section' },
  { name: 'paragraph', snippet: 'paragraph{', meta: 'section' },
  { name: 'subparagraph', snippet: 'subparagraph{', meta: 'section' },
  { name: 'textbf', snippet: 'textbf{', meta: 'format' },
  { name: 'textit', snippet: 'textit{', meta: 'format' },
  { name: 'texttt', snippet: 'texttt{', meta: 'format' },
  { name: 'textsc', snippet: 'textsc{', meta: 'format' },
  { name: 'textrm', snippet: 'textrm{', meta: 'format' },
  { name: 'textsf', snippet: 'textsf{', meta: 'format' },
  { name: 'emph', snippet: 'emph{', meta: 'format' },
  { name: 'underline', snippet: 'underline{', meta: 'format' },
  { name: 'textcolor', snippet: 'textcolor{', meta: 'format' },
  { name: 'textsubscript', snippet: 'textsubscript{', meta: 'format' },
  { name: 'textsuperscript', snippet: 'textsuperscript{', meta: 'format' },
  { name: 'tiny', snippet: 'tiny', meta: 'size' },
  { name: 'scriptsize', snippet: 'scriptsize', meta: 'size' },
  { name: 'footnotesize', snippet: 'footnotesize', meta: 'size' },
  { name: 'small', snippet: 'small', meta: 'size' },
  { name: 'normalsize', snippet: 'normalsize', meta: 'size' },
  { name: 'large', snippet: 'large', meta: 'size' },
  { name: 'Large', snippet: 'Large', meta: 'size' },
  { name: 'LARGE', snippet: 'LARGE', meta: 'size' },
  { name: 'huge', snippet: 'huge', meta: 'size' },
  { name: 'Huge', snippet: 'Huge', meta: 'size' },
  { name: 'label', snippet: 'label{', meta: 'ref' },
  { name: 'ref', snippet: 'ref{', meta: 'ref' },
  { name: 'pageref', snippet: 'pageref{', meta: 'ref' },
  { name: 'eqref', snippet: 'eqref{', meta: 'ref' },
  { name: 'cite', snippet: 'cite{', meta: 'ref' },
  { name: 'citep', snippet: 'citep{', meta: 'ref' },
  { name: 'citet', snippet: 'citet{', meta: 'ref' },
  { name: 'bibliography', snippet: 'bibliography{', meta: 'ref' },
  { name: 'bibliographystyle', snippet: 'bibliographystyle{', meta: 'ref' },
  { name: 'addbibresource', snippet: 'addbibresource{', meta: 'ref' },
  { name: 'nocite', snippet: 'nocite{*}', meta: 'ref' },
  { name: 'includegraphics', snippet: 'includegraphics[width=0.8\\textwidth]{', meta: 'figure' },
  { name: 'caption', snippet: 'caption{', meta: 'figure' },
  { name: 'centering', snippet: 'centering', meta: 'figure' },
  { name: 'hline', snippet: 'hline', meta: 'table' },
  { name: 'multicolumn', snippet: 'multicolumn{', meta: 'table' },
  { name: 'multirow', snippet: 'multirow{', meta: 'table' },
  { name: 'cline', snippet: 'cline{', meta: 'table' },
  { name: 'toprule', snippet: 'toprule', meta: 'table' },
  { name: 'midrule', snippet: 'midrule', meta: 'table' },
  { name: 'bottomrule', snippet: 'bottomrule', meta: 'table' },
  { name: 'frac', snippet: 'frac{', meta: 'math' },
  { name: 'dfrac', snippet: 'dfrac{', meta: 'math' },
  { name: 'tfrac', snippet: 'tfrac{', meta: 'math' },
  { name: 'sqrt', snippet: 'sqrt{', meta: 'math' },
  { name: 'sum', snippet: 'sum_{', meta: 'math' },
  { name: 'prod', snippet: 'prod_{', meta: 'math' },
  { name: 'int', snippet: 'int_{', meta: 'math' },
  { name: 'oint', snippet: 'oint_{', meta: 'math' },
  { name: 'iint', snippet: 'iint_{', meta: 'math' },
  { name: 'lim', snippet: 'lim_{', meta: 'math' },
  { name: 'infty', snippet: 'infty', meta: 'math' },
  { name: 'partial', snippet: 'partial', meta: 'math' },
  { name: 'nabla', snippet: 'nabla', meta: 'math' },
  { name: 'cdot', snippet: 'cdot', meta: 'math' },
  { name: 'times', snippet: 'times', meta: 'math' },
  { name: 'pm', snippet: 'pm', meta: 'math' },
  { name: 'mp', snippet: 'mp', meta: 'math' },
  { name: 'leq', snippet: 'leq', meta: 'math' },
  { name: 'geq', snippet: 'geq', meta: 'math' },
  { name: 'neq', snippet: 'neq', meta: 'math' },
  { name: 'approx', snippet: 'approx', meta: 'math' },
  { name: 'equiv', snippet: 'equiv', meta: 'math' },
  { name: 'sim', snippet: 'sim', meta: 'math' },
  { name: 'propto', snippet: 'propto', meta: 'math' },
  { name: 'rightarrow', snippet: 'rightarrow', meta: 'math' },
  { name: 'leftarrow', snippet: 'leftarrow', meta: 'math' },
  { name: 'Rightarrow', snippet: 'Rightarrow', meta: 'math' },
  { name: 'Leftarrow', snippet: 'Leftarrow', meta: 'math' },
  { name: 'leftrightarrow', snippet: 'leftrightarrow', meta: 'math' },
  { name: 'Leftrightarrow', snippet: 'Leftrightarrow', meta: 'math' },
  { name: 'mapsto', snippet: 'mapsto', meta: 'math' },
  { name: 'overline', snippet: 'overline{', meta: 'math' },
  { name: 'underline', snippet: 'underline{', meta: 'math' },
  { name: 'hat', snippet: 'hat{', meta: 'math' },
  { name: 'bar', snippet: 'bar{', meta: 'math' },
  { name: 'vec', snippet: 'vec{', meta: 'math' },
  { name: 'dot', snippet: 'dot{', meta: 'math' },
  { name: 'ddot', snippet: 'ddot{', meta: 'math' },
  { name: 'tilde', snippet: 'tilde{', meta: 'math' },
  { name: 'mathbb', snippet: 'mathbb{', meta: 'math' },
  { name: 'mathcal', snippet: 'mathcal{', meta: 'math' },
  { name: 'mathfrak', snippet: 'mathfrak{', meta: 'math' },
  { name: 'mathrm', snippet: 'mathrm{', meta: 'math' },
  { name: 'text', snippet: 'text{', meta: 'math' },
  { name: 'left', snippet: 'left', meta: 'math' },
  { name: 'right', snippet: 'right', meta: 'math' },
  { name: 'binom', snippet: 'binom{', meta: 'math' },
  { name: 'alpha', snippet: 'alpha', meta: 'greek' },
  { name: 'beta', snippet: 'beta', meta: 'greek' },
  { name: 'gamma', snippet: 'gamma', meta: 'greek' },
  { name: 'delta', snippet: 'delta', meta: 'greek' },
  { name: 'epsilon', snippet: 'epsilon', meta: 'greek' },
  { name: 'varepsilon', snippet: 'varepsilon', meta: 'greek' },
  { name: 'zeta', snippet: 'zeta', meta: 'greek' },
  { name: 'eta', snippet: 'eta', meta: 'greek' },
  { name: 'theta', snippet: 'theta', meta: 'greek' },
  { name: 'vartheta', snippet: 'vartheta', meta: 'greek' },
  { name: 'iota', snippet: 'iota', meta: 'greek' },
  { name: 'kappa', snippet: 'kappa', meta: 'greek' },
  { name: 'lambda', snippet: 'lambda', meta: 'greek' },
  { name: 'mu', snippet: 'mu', meta: 'greek' },
  { name: 'nu', snippet: 'nu', meta: 'greek' },
  { name: 'xi', snippet: 'xi', meta: 'greek' },
  { name: 'pi', snippet: 'pi', meta: 'greek' },
  { name: 'rho', snippet: 'rho', meta: 'greek' },
  { name: 'sigma', snippet: 'sigma', meta: 'greek' },
  { name: 'tau', snippet: 'tau', meta: 'greek' },
  { name: 'upsilon', snippet: 'upsilon', meta: 'greek' },
  { name: 'phi', snippet: 'phi', meta: 'greek' },
  { name: 'varphi', snippet: 'varphi', meta: 'greek' },
  { name: 'chi', snippet: 'chi', meta: 'greek' },
  { name: 'psi', snippet: 'psi', meta: 'greek' },
  { name: 'omega', snippet: 'omega', meta: 'greek' },
  { name: 'Gamma', snippet: 'Gamma', meta: 'greek' },
  { name: 'Delta', snippet: 'Delta', meta: 'greek' },
  { name: 'Theta', snippet: 'Theta', meta: 'greek' },
  { name: 'Lambda', snippet: 'Lambda', meta: 'greek' },
  { name: 'Xi', snippet: 'Xi', meta: 'greek' },
  { name: 'Pi', snippet: 'Pi', meta: 'greek' },
  { name: 'Sigma', snippet: 'Sigma', meta: 'greek' },
  { name: 'Phi', snippet: 'Phi', meta: 'greek' },
  { name: 'Psi', snippet: 'Psi', meta: 'greek' },
  { name: 'Omega', snippet: 'Omega', meta: 'greek' },
  { name: 'sin', snippet: 'sin', meta: 'operator' },
  { name: 'cos', snippet: 'cos', meta: 'operator' },
  { name: 'tan', snippet: 'tan', meta: 'operator' },
  { name: 'cot', snippet: 'cot', meta: 'operator' },
  { name: 'sec', snippet: 'sec', meta: 'operator' },
  { name: 'csc', snippet: 'csc', meta: 'operator' },
  { name: 'arcsin', snippet: 'arcsin', meta: 'operator' },
  { name: 'arccos', snippet: 'arccos', meta: 'operator' },
  { name: 'arctan', snippet: 'arctan', meta: 'operator' },
  { name: 'sinh', snippet: 'sinh', meta: 'operator' },
  { name: 'cosh', snippet: 'cosh', meta: 'operator' },
  { name: 'tanh', snippet: 'tanh', meta: 'operator' },
  { name: 'log', snippet: 'log', meta: 'operator' },
  { name: 'ln', snippet: 'ln', meta: 'operator' },
  { name: 'exp', snippet: 'exp', meta: 'operator' },
  { name: 'min', snippet: 'min', meta: 'operator' },
  { name: 'max', snippet: 'max', meta: 'operator' },
  { name: 'sup', snippet: 'sup', meta: 'operator' },
  { name: 'inf', snippet: 'inf', meta: 'operator' },
  { name: 'det', snippet: 'det', meta: 'operator' },
  { name: 'dim', snippet: 'dim', meta: 'operator' },
  { name: 'ker', snippet: 'ker', meta: 'operator' },
  { name: 'hom', snippet: 'hom', meta: 'operator' },
  { name: 'deg', snippet: 'deg', meta: 'operator' },
  { name: 'hspace', snippet: 'hspace{', meta: 'spacing' },
  { name: 'vspace', snippet: 'vspace{', meta: 'spacing' },
  { name: 'quad', snippet: 'quad', meta: 'spacing' },
  { name: 'qquad', snippet: 'qquad', meta: 'spacing' },
  { name: 'newline', snippet: 'newline', meta: 'spacing' },
  { name: 'newpage', snippet: 'newpage', meta: 'spacing' },
  { name: 'clearpage', snippet: 'clearpage', meta: 'spacing' },
  { name: 'pagebreak', snippet: 'pagebreak', meta: 'spacing' },
  { name: 'linebreak', snippet: 'linebreak', meta: 'spacing' },
  { name: 'newcommand', snippet: 'newcommand{\\', meta: 'define' },
  { name: 'renewcommand', snippet: 'renewcommand{\\', meta: 'define' },
  { name: 'newenvironment', snippet: 'newenvironment{', meta: 'define' },
  { name: 'providecommand', snippet: 'providecommand{\\', meta: 'define' },
  { name: 'DeclareMathOperator', snippet: 'DeclareMathOperator{\\', meta: 'define' },
  { name: 'footnote', snippet: 'footnote{', meta: 'misc' },
  { name: 'marginpar', snippet: 'marginpar{', meta: 'misc' },
  { name: 'noindent', snippet: 'noindent', meta: 'misc' },
  { name: 'raggedright', snippet: 'raggedright', meta: 'misc' },
  { name: 'raggedleft', snippet: 'raggedleft', meta: 'misc' },
  { name: 'hfill', snippet: 'hfill', meta: 'misc' },
  { name: 'vfill', snippet: 'vfill', meta: 'misc' },
  { name: 'item', snippet: 'item ', meta: 'list' },
  { name: 'setlength', snippet: 'setlength{', meta: 'layout' },
  { name: 'geometry', snippet: 'geometry{', meta: 'layout' },
  { name: 'pagenumbering', snippet: 'pagenumbering{', meta: 'layout' },
  { name: 'pagestyle', snippet: 'pagestyle{', meta: 'layout' },
  { name: 'thispagestyle', snippet: 'thispagestyle{', meta: 'layout' },
  { name: 'url', snippet: 'url{', meta: 'misc' },
  { name: 'href', snippet: 'href{', meta: 'misc' },
  { name: 'phantom', snippet: 'phantom{', meta: 'misc' },
  { name: 'mbox', snippet: 'mbox{', meta: 'misc' },
  { name: 'makebox', snippet: 'makebox[', meta: 'misc' },
  { name: 'framebox', snippet: 'framebox{', meta: 'misc' },
  { name: 'parbox', snippet: 'parbox{', meta: 'misc' },
  { name: 'rule', snippet: 'rule{', meta: 'misc' },
];

export const LATEX_ENVIRONMENTS = [
  { name: 'document' },
  { name: 'figure' },
  { name: 'table' },
  { name: 'tabular' },
  { name: 'tabularx' },
  { name: 'longtable' },
  { name: 'equation' },
  { name: 'equation*' },
  { name: 'align' },
  { name: 'align*' },
  { name: 'gather' },
  { name: 'gather*' },
  { name: 'multline' },
  { name: 'multline*' },
  { name: 'split' },
  { name: 'cases' },
  { name: 'matrix' },
  { name: 'pmatrix' },
  { name: 'bmatrix' },
  { name: 'vmatrix' },
  { name: 'Vmatrix' },
  { name: 'Bmatrix' },
  { name: 'array' },
  { name: 'itemize' },
  { name: 'enumerate' },
  { name: 'description' },
  { name: 'abstract' },
  { name: 'verbatim' },
  { name: 'lstlisting' },
  { name: 'minted' },
  { name: 'quote' },
  { name: 'quotation' },
  { name: 'verse' },
  { name: 'center' },
  { name: 'flushleft' },
  { name: 'flushright' },
  { name: 'minipage' },
  { name: 'theorem' },
  { name: 'proof' },
  { name: 'lemma' },
  { name: 'definition' },
  { name: 'corollary' },
  { name: 'proposition' },
  { name: 'example' },
  { name: 'remark' },
  { name: 'note' },
  { name: 'frame' },
  { name: 'block' },
  { name: 'columns' },
  { name: 'column' },
  { name: 'tikzpicture' },
  { name: 'pgfplot' },
  { name: 'axis' },
  { name: 'scope' },
  { name: 'thebibliography' },
  { name: 'appendix' },
  { name: 'landscape' },
  { name: 'sidewaystable' },
  { name: 'sidewaysfigure' },
  { name: 'subfigure' },
  { name: 'wrapfigure' },
];
